export const PARTNERS_DATA = [
    {
        version: "8.0",
        sponsors: [
            { name: "IITMAA", role: "Scalability Partner", logo: "/partners/IITMAA.png" },
            { name: "TE Connectivity", role: "Partner", logo: "/partners/polamcote-logo2.png" },
            { name: "Arcelor Mittal", role: "Materials Partner", logo: "/partners/Arcelormittal-logo.svg.png" },
            { name: "Indian Railways", role: "Materials Partner", logo: "/partners/IndianRailways.png" },
            { name: "Wabtec", role: "Software Sponsor", logo: "/partners/wabtec.png" },
            { name: "Harting", role: "Systems Sponsor", logo: "/partners/Harting.png.png" },
            { name: "Ansys", role: "Software Sponsor", logo: "/partners/ansys.png" },
            { name: "Vector", role: "CAN / Ethernet Tools Sponsor", logo: "/partners/vector.png" },
            { name: "Swagelok", role: "Silver Sponsor · Pneumatics", logo: "/partners/swagelok.png" },
            { name: "Aditya Birla", role: "Silver Sponsor", logo: "/partners/Hindalco.png" },
            { name: "Composites Tomorrow", role: "Silver Sponsor", logo: "/partners/CompositesTomorrow.png" },
        ],
    },
    {
        version: "6.0",
        sponsors: [
            { name: "Tube Investments of India", role: "Scalability Partner", logo: "/partners/tube-investments.svg" },
            { name: "L&T Heavy Civil Infrastructure", role: "Partner", logo: "/partners/images.jpeg" },
            { name: "Arcelor Mittal", role: "Materials Partner", logo: "/partners/Arcelormittal-logo.svg.png" },
            { name: "Ansys", role: "Software Sponsor", logo: "/partners/ansys.png" },
            { name: "Altium", role: "Systems Sponsor", logo: "/partners/altium.png" },
            { name: "Vector", role: "CAN / Ethernet Tools Sponsor", logo: "/partners/vector.png" },
        ],
    },
    {
        version: "5.0",
        sponsors: [
            { name: "Tube Investments of India", role: "Scalability Partner", logo: "/partners/tube-investments.svg" },
            { name: "L&T Heavy Civil Infrastructure", role: "Partner", logo: "/partners/images.jpeg" },
            { name: "Arcelor Mittal", role: "Materials Partner", logo: "/partners/Arcelormittal-logo.svg.png" },
            { name: "Ansys", role: "Software Sponsor", logo: "/partners/ansys.png" },
            { name: "Altium", role: "Systems Sponsor", logo: "/partners/altium.png" },
            { name: "Vector", role: "CAN / Ethernet Tools Sponsor", logo: "/partners/vector.png" },
        ],
    },
    {
        version: "4.0",
        sponsors: [
            { name: "Deloitte", role: "Title Sponsor", logo: "/partners/379251LOGO.jpg" },
            { name: "Comsol", role: "Gold Sponsor", logo: "/partners/Comsol.png" },
            { name: "Ansys", role: "Silver Sponsor · Simulation", logo: "/partners/ansys.png" },
            { name: "Swagelok", role: "Silver Sponsor · Pneumatics", logo: "/partners/swagelok.png" },
            { name: "Arus MR Tech", role: "Supporting · Suspension", logo: "/partners/arus.png" },
            { name: "Benewake", role: "Supporting · Sensing", logo: "/partners/benewake-logo.png" },
        ],
    },
    {
        version: "3.0",
        sponsors: [
            { name: "Deloitte", role: "Title Sponsor", logo: "/partners/379251LOGO.jpg" },
            { name: "Comsol", role: "Gold Sponsor", logo: "/partners/Comsol.png" },
            { name: "Ansys", role: "Silver Sponsor · Simulation", logo: "/partners/ansys.png" },
            { name: "Swagelok", role: "Silver Sponsor · Pneumatics", logo: "/partners/swagelok.png" },
            { name: "Arus MR Tech", role: "Supporting · Suspension", logo: "/partners/arus.png" },
            { name: "Benewake", role: "Supporting · Sensing", logo: "/partners/benewake.png" },
        ],
    },
    {
        version: "2.0",
        sponsors: [
            { name: "Tube Investments of India", role: "Title Sponsor", logo: "/partners/tube-investments.svg" },
            { name: "Hexaware", role: "Platinum Sponsor", logo: "/partners/hexaware.png" },
            { name: "SMC", role: "Platinum Sponsor", logo: "/partners/smc.png" },
            { name: "Comsol", role: "Gold Sponsor", logo: "/partners/Comsol.png" },
            { name: "Sparton", role: "Silver Sponsor", logo: "/partners/sparton.png" },
            { name: "Hasura", role: "Silver Sponsor", logo: "/partners/Hasura.png" },
            { name: "Rupee Circle", role: "Silver Sponsor", logo: "/partners/RupeeCircle.png" },
            { name: "Olympia", role: "Silver Sponsor", logo: "/partners/Olympia.jpg" },
            { name: "Mouser", role: "Silver Sponsor", logo: "/partners/mouser.png" },
            { name: "Melasta", role: "Silver Sponsor", logo: "/partners/Melasta.png" },
            { name: "Autodesk", role: "Silver Sponsor", logo: "/partners/autodesk.png" },
            { name: "Parker", role: "Supporting Sponsor", logo: "/partners/Parker.png" },
            { name: "Albright International", role: "Supporting Sponsor", logo: "/partners/albright.png" },
            { name: "Ketto", role: "Supporting Sponsor", logo: "/partners/ketto.png" },
            { name: "Fab Heads", role: "Supporting Sponsor", logo: "/partners/Fabheads.png" },
            { name: "MGM Controllers", role: "Supporting Sponsor", logo: "/partners/mgm.png" },
            { name: "Inverion", role: "Supporting Sponsor", logo: "/partners/Inverion.png" },
            { name: "Compatech", role: "Supporting Sponsor", logo: "/partners/compacTech.png" },
        ],
    },
];
